version: '3.8'

services:
  haxball-host:
    build:
      context: .
      network: host
    container_name: haxball-host
    restart: unless-stopped
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
